CREATE TABLE tb_mentorship_sessions(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL UNIQUE,
    dev_id BIGINT NOT NULL,
    mentor_id BIGINT NOT NULL,
    topic VARCHAR(255),
    scheduled_at TIMESTAMP WITH TIME ZONE,
    duration BIGINT,  -- Armazena em segundos
    platform_url VARCHAR(255),
    status VARCHAR(30),

    CONSTRAINT fk_request_id FOREIGN KEY (request_id) REFERENCES tb_mentorship_requests(id),
    CONSTRAINT fk_dev_id FOREIGN KEY (dev_id) REFERENCES tb_users(id),
    CONSTRAINT fk_mentor FOREIGN KEY (mentor_id) REFERENCES tb_users(id)
);